# -*- coding: utf-8 -*-
"""GA_MINI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-yPKMqdcmhcjSeR5wa-Q6L-lxzpOh_hl
"""


import numpy as np
import halbachFields
import random
from deap import algorithms, base, tools,creator
import multiprocessing
import ctypes
import time
import matplotlib.pyplot as plt
from HallbachRing_Edit_1 import HallbachRing
import pandas as pd
from IPython.display import display
import GA_documentation as gadoc
# Magnet Array Design

# Ring Parameters
InnerBoreDiameter = 100                 # Inner Diameter of the Ring
OuterBoreDiameter = 180                 # Outer Diameter of the Ring
magnetSize = 12                         # Length of cube
magnetSize_meter = magnetSize * 1e-3    # Length of cube (converted to meters)
arrayLength = 240                       # Length of scanner

amountBand = np.array([1])        # Amount of bands within a ring
bandRadiiGap = np.linspace(0, 50, 15)    # Space between Bands
magnetSpace = np.linspace(3, 10, 15)     # Space Between Magnets
ringSep = np.array([24])        # Space between Ring Centers
bandSep = np.linspace(3, 10, 7)         # Space between Bore and 1st band

# Calculate the number of rings for each ring separation
ringNr = arrayLength / ringSep
ringNr_int = ringNr.astype(int) + 1

# Initialize a list to store the ring positions for each ring separation
ringPositions = []

for i in range(len(ringNr_int)):
    # Calculate the positions for the current number of rings
    positions = np.linspace(-arrayLength / 2, arrayLength / 2, ringNr_int[i])
    # Append the calculated positions to the list
    ringPositions.append(positions)

print(ringPositions)
# Set threshold for BandRadius
bandRadiusThreshold = (OuterBoreDiameter/2)-magnetSize

#Default Values
BandRadii = [-1]        # Default minimum radius for bands
MagnetInBandNr = [-1]   # Default maximum number of magnets in a band

# Initialize lists to store data
data = []

# Iterate over combinations of amountBand, bandRadiiGap, and magnetSpace
for i in range(len(amountBand)):
    for j in range(len(bandRadiiGap)):
        for l in range(len(bandSep)):
            for k in range(len(magnetSpace)):

                    # Skip iterations where bandRadiiGap is varied but amountBand is 1
                    if amountBand[i] == 1 and bandRadiiGap[j] != 0:
                        continue

                    # Create instance of HallbachRing for current parameters
                    singleHallbachRing = HallbachRing(
                        magnetSize,
                        InnerBoreDiameter / 2,
                        OuterBoreDiameter / 2, 
                        BandRadii * amountBand[i],
                        MagnetInBandNr * amountBand[i],
                        bandRadiiGap[j],
                        magnetSpace[k],
                        bandSep[l]
                    )
                    bandRadius, bandMagnetNr = singleHallbachRing.getParameters()


                    # Check if any BandRadius exceeds the threshold
                    if any(r > bandRadiusThreshold for r in bandRadius):
                        continue


                    # Append data as a dictionary to the list
                    data.append({
                        'BandNumber': amountBand[i],
                        'BandRadiiGap': bandRadiiGap[j],
                        'MagnetSpace': magnetSpace[k],
                        'BandSeparation': bandSep[l],
                        'BandRadius': bandRadius,
                        'MagnetNr': bandMagnetNr
                    })

# Convert list of dictionaries to Pandas DataFrame
df = pd.DataFrame(data)


# Display the DataFrame in a Jupyter notebook
display(df)

# Define conversion factor from mm to meters
mm_to_m = 1 / 1000

# Number of decimal places to round to
decimal_places = 8

# Create a new list to store the converted and rounded data
converted_data = []

# Iterate over the original data to convert values to meters and round them
for row in data:
    converted_row = {
        'BandNumber': row['BandNumber'],
        'BandRadiiGap': round(row['BandRadiiGap'] * mm_to_m, decimal_places),
        'MagnetSpace': round(row['MagnetSpace'] * mm_to_m, decimal_places),
        'BandSeparation': round(row['BandSeparation'] * mm_to_m, decimal_places),
        'BandRadius': [round(r * mm_to_m, decimal_places) for r in row['BandRadius']],
        'MagnetNr': row['MagnetNr']
    }
    converted_data.append(converted_row)

# Convert the converted data list to a DataFrame
df_meters = pd.DataFrame(converted_data)

# Display the converted DataFrame in a Jupyter notebook
display(df_meters)
'''
# Iterate over each row in the DataFrame and draw the corresponding ring
for index, row in df.iterrows():
    # Create an instance of HallbachRing for the current row configuration
    hallbachRing = HallbachRing(
        magnetSize,
        InnerBoreDiameter / 2,
        row['BandRadius'],
        row['MagnetNr'],
        row['BandRadiiGap'],
        row['MagnetSpace'],
        row['BandSeparation']
    )

    # Plot the ring configuration
    hallbachRing.drawHallbach()
'''
resolution = 1

popSim = 10000
maxGeneration = 100
DSV = 60*1e-3

ringPositionsL = ringPositions[0]*1e-3
print(ringPositionsL)
###################################################################################################################
##########################################                               ##########################################
##########################################     Create spherical mask     ##########################################
##########################################                               ##########################################
###################################################################################################################

simDimensions = (DSV,DSV,DSV)

coordinateAxis = np.linspace(-simDimensions[0]/2,simDimensions[0]/2,int(1e3*simDimensions[0]/resolution + 1))
coords = np.meshgrid(coordinateAxis, coordinateAxis, coordinateAxis)

mask = np.zeros(np.shape(coords[0]))
mask[np.square(coords[0]) + np.square(coords[1]) + np.square(coords[2]) <= (DSV/2)**2] = 1

octantMask = np.copy(mask)
octantMask[coords[0] < 0] = 0
octantMask[coords[1] < 0] = 0
octantMask[coords[2] < 0] = 0




stop_event, monitor_thread = gadoc.track_system_usage(interval=1)


# Symmetrical from ring position 0 and up? SDP

ringPositionsSymmetery = ringPositionsL[ringPositionsL >= 0]

# Initialize shimFields
num_positions = np.size(ringPositionsSymmetery)  # Number of positions
num_rings = df_meters.shape[0]  # Number of sizes based on the DataFrame
shimFields = np.zeros((int(np.sum(octantMask)), num_positions, num_rings))

# Iterate over positions and sizes from the DataFrame
for positionIdx, position in enumerate(ringPositionsSymmetery):
    for sizeIdx in range(num_rings):
        # Extract parameters from the DataFrame
        row = df_meters.iloc[sizeIdx]
        if position == 0:
            rings = (0,)
        else:
            rings = (-position, position)

        # Initialize fieldData to None
        fieldData = None

        # Loop through the number of bands and sum the field data for each band
        for band_idx in range(int(row['BandNumber'])):
            band_field_data = halbachFields.createHalbach(
                numMagnets=int(row['MagnetNr'][band_idx]),
                rings=rings,
                radius=row['BandRadius'][band_idx],
                magnetSize=magnetSize_meter,
                resolution=1e3/resolution,
                simDimensions=simDimensions
            )
            if fieldData is None:
                fieldData = np.zeros_like(band_field_data)  # Initialize fieldData with the shape of band_field_data

            fieldData += band_field_data
            # Mask the shimfield data SDP
        shimFields[:, positionIdx, sizeIdx] = fieldData[octantMask == 1, 0]

def fieldError(shimVector):
    field = np.zeros(np.size(sharedShimMagnetsFields,0))
    for idx1 in range(0,np.size(shimVector)):
        field += sharedShimMagnetsFields[:,idx1,shimVector[idx1]]

    # Homogeneity error
    homogeneity_error = ((np.max(field) - np.min(field)) / np.mean(field)) * 1e6

        # Field strength error
    mean_field_strength = np.mean(field)
    field_strength_error = np.abs(mean_field_strength - 0.05) * 1e6

    # Combine the two errors into a single fitness score, prioritizing according to weighting
    total_error = (0.5 * homogeneity_error) + (0.5 * field_strength_error)
    return (total_error,homogeneity_error, mean_field_strength)

sharedShimMagnetsFields_base = multiprocessing.Array(ctypes.c_double, np.size(shimFields))
sharedShimMagnetsFields = np.ctypeslib.as_array(sharedShimMagnetsFields_base.get_obj())
sharedShimMagnetsFields = sharedShimMagnetsFields.reshape(np.size(shimFields, 0), np.size(shimFields, 1), np.size(shimFields, 2))
sharedShimMagnetsFields[...] = shimFields[...]

random.seed()

creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)

toolbox = base.Toolbox()
toolbox.register("attr_bool", random.randint, 0, np.size(sharedShimMagnetsFields, 2) - 1)
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_bool, np.size(sharedShimMagnetsFields, 1))
toolbox.register("population", tools.initRepeat, list, toolbox.individual)
toolbox.register("evaluate", fieldError)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)

pop = toolbox.population(n=popSim)
CXPB, MUTPB = 0.55, 0.4
print("Start of evolution")
startTime = time.time()
fitnesses = list(map(toolbox.evaluate, pop))
bestError = np.inf

for ind, fit in zip(pop, fitnesses):
    ind.fitness.values = (fit[0],)  # Only store total_error as fitness
    ind.homogeneity_error = fit[1]
    ind.field_strength_error = fit[2]

fits = [ind.fitness.values[0] for ind in pop]

g = 0
minTracker = np.zeros((maxGeneration))
startEvolution = time.time()

while g < maxGeneration:
  startTime = time.time()
  g = g + 1
  print("-- Generation %i --" % g)

  offspring = toolbox.select(pop, len(pop))
  offspring = list(map(toolbox.clone, offspring))

  for child1, child2 in zip(offspring[::2], offspring[1::2]):
      if random.random() < CXPB:
          toolbox.mate(child1, child2)
          del child1.fitness.values
          del child2.fitness.values

  for mutant in offspring:
      if random.random() < MUTPB:
          toolbox.mutate(mutant)
          del mutant.fitness.values

  invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
  fitnesses = map(toolbox.evaluate, invalid_ind)
  for ind, fit in zip(invalid_ind, fitnesses):
      ind.fitness.values = (fit[0],)  # Only store total_error as fitness
      ind.homogeneity_error = fit[1]
      ind.field_strength_error = fit[2]

  pop[:] = offspring
  fits = [ind.fitness.values[0] for ind in pop]

  if min(fits) < bestError:
      best = tools.selBest(pop, 1)[0]
      print("BEST VECTOR: " + str(best))
      print("  → Total error: %.2f " % best.fitness.values[0])
      print("  → Homogeneity: %.2f ppm" % best.homogeneity_error)
      print("  → Field strength mean: %.8f T" % best.field_strength_error)
      bestError = min(fits)
      actualBestVector = tools.selBest(pop, 1)[0]

  minTracker[g-1] = min(fits)
  print("Evaluation took " + str(time.time() - startTime) + " seconds")
  print("Minimum: %i ppm" % min(fits))

print("-- End of (successful) evolution --")
best_ind = tools.selBest(pop, 1)[0]
print("Best individual is %s, %s" % (best_ind, best_ind.fitness.values))
# Print homogeneity and field strength of the best individual
print("  → Homogeneity: %.2f ppm" % best_ind.homogeneity_error)
print("  → Field strength mean: %.8f T" % best_ind.field_strength_error)
best_vector = best_ind

stop_event.set()
monitor_thread.join()
# Save the full Halbach configurations
gadoc.save_hallbach_configurations(df_meters)

# Save minimum fitness per generation
gadoc.save_fitness_per_generation(minTracker)

# Save the best individual vector
gadoc.save_best_vector(best_vector, df_meters, ringPositionsSymmetery)

for pos_idx, df_idx in enumerate(best_vector):
    row = df_meters.iloc[df_idx]
    position = ringPositionsSymmetery[pos_idx]

    if position == 0:
        rings = (0,)
    else:
        rings = (-position, position)

    try:
        hallbachRing = HallbachRing(
            magnetSize,  # already in mm
            InnerBoreDiameter / 2,  # in mm
            OuterBoreDiameter / 2,
            [r*1000 for r in row['BandRadius']],  # convert back to mm
            row['MagnetNr'],
            row['BandRadiiGap']*1000,  # convert to mm
            row['MagnetSpace']*1000,   # convert to mm
            row['BandSeparation']*1000 # convert to mm
            )
        hallbachRing.drawHallbach()
    except ValueError as e:
        print(f"Skipping invalid ring at position {position}: {e}")